#!/bin/bash

title="Что выбираем?"
MENU=(
    "Запустить Airgeddon"
    "Запустить Wifite"
    "Запустить WiFi-autopwner"
    "Завершение работы"
)
select menu in "${MENU[@]}" ; do
    case $REPLY in
        1) sudo bash ~/wifitest/airgeddon/airgeddon.sh ;;
        2) sudo wifite ;;
        3) sudo bash ~/wifitest/WiFi-autopwner/wifi-autopwner.sh ;;
        4) break ;;
    esac
done
